language: node_js
services:
  - mongodb
node_js:
  - 12
before_script:
  - cp ./config/config.js.tpl ./config/development.js
  - cp ./config/config.js.tpl ./config/production.js
  - cp ./config/config.js.tpl ./config/test.js
  - export OPENWEATHER_API_APPID=$OPENWEATHER_API_APPID
  - export MONGO_URL=$MONGO_URL
script:
  - npm install
  - npm test
