language: node_js
services:
  - mongodb
node_js:
  - 8
before_script:
  - cp ./config/config.js.tpl ./config/development.js
  - cp ./config/config.js.tpl ./config/production.js
  - touch ./config/test.js
  - echo $TEST_CONFIG >> ./config/test.js
script:
  - npm install
  - npm test
